### PR TITLE
Update map.md

### PR DESCRIPTION
**Pull request by noraa-july-stoke**
Hi, I am wanting to make a submission for the map entry for review. I am willing to keep working on it and add more detailed explanations down the road but this is all I have time for currently. I hope you like it.

### CODE REVIEW

**Comment by noraa-july-stoke** [comment]
Is there a style guide I can reference to get this to pass?

**Comment by wilfredinni** [comment]
Hi! Thank you for your patience, I was on vacation and refused to bring a computer with me, hahaha. Those check failed because of some dependencies of the webpage. It is all good now.

>  I am willing to keep working on it and add more detailed explanations down the road

That is awesome!

**Comment by noraa-july-stoke** [comment]
It is okay sorry if i sent the question more than one place! I just didn't know what places you check notifications regularly! That's awesome I'm glad to hear you got to have a (I'm sure well-deserved) break!

**Comment by noraa-july-stoke** [comment]
Also, if you have any needs for more articles to be written feel free to send them my way! I'm not the most advanced at python by any means but I know a lot of the basics and doing stuff like this just makes me better!

**Pull request merged**
