### PR TITLE
Add section on comprehensions, convert to jupyter notebook

### PR DESCRIPTION
**Pull request by gsemet**
comprehension, string formatting

### CODE REVIEW

**Comment by wilfredinni** [comment]
First, i wanted to thank you for your additions, they are very good. But since some of them were made a few hours ago, among which string formatting is already present, i can not perform the merge pull request (due to conflicts).

If you can make the additions and changes from the last commit, i would appreciate it.

**Comment by gsemet** [comment]
Sure !

**Comment by gsemet** [comment]
New change: convertion to jupyter notebook. Great for students, where they can evaluate themselve the result of each command.

I had to rework the section to be compatible always with `>>>` REPL syntax, and hack a bit in the notebook to have a clean, notebook-like syntax, but overall I am pretty satisfied with the result. this allows student to open this notebook and play with each commands.

I do not have fixed all issues, one being the hypterlinks does not work the same inside jupyter (need to keep the case). This would require a bit of python to properly fix, I will try to do it if i find the time

**Comment by wilfredinni** [comment]
Thank you. This is awesome!

**Pull request merged**
