### PR TITLE
Various fixes

### PR DESCRIPTION
**Pull request by MaT1g3R**
Sorry for the big PR, I looked over the README and fixed various issues, the one that stood out
the most for me was not using `with` to open files.

There are also some suggestions I would like to make, I didn't want to change them directly in the code since they are just some ideas I'm throwing around:

* Use string formatting instead of adding strings together
* Talk about `pathlib` instead of `os.path`
* Perhaps also distribute this as a Jupyter Notebook/a collection of Jupyter Notebooks

I think this is a pretty awesome project, and should be a really useful resource for beginners.

### CODE REVIEW

**Comment by wilfredinni** [comment]
Thank you, those are realy good corrections.

- Use string formatting instead of adding strings together:
I was thinkin to add `.format()`, the `Template` form the `string` library and the `Formatted String Literal`.
- Talk about pathlib instead of os.path:
How about to have both of them?
- Perhaps also distribute this as a Jupyter Notebook/a collection of Jupyter Notebooks
That is a realy good idea, sadly, i just know the basics of it (ill chek it out)

**Comment by MaT1g3R** [comment]
Going back to those points:

* I think `str.format` and `f-strings` are good to talk about, the `Template` from `string` is a bit more niche and imo it's not something beginners should worry about (I haven't seen it used anywhere in the wild)

* It's a good idea to talk about both `os.path` and `pathlib`, I think `pathlib` has a nicer API in general and should be preferred over `os.path`, but that's just my personal preference

* The reason for Jupyter Notebooks is that there's a lot of code examples in the file, and Jupyter Notebook can run those code snippets (GitHub will even render them), however I'm not sure how it would handle reading/writing files

**Comment by wilfredinni** [comment]
do you think it is a good idea to add projects to the repository to have the different topics to add ordered in a todo list?

**Comment by MaT1g3R** [comment]
I think that is a good idea, especially when this repo grows larger and larger in size, keeping track of a TODO list can definitely be beneficial.

**Comment by wilfredinni** [comment]
Done.

**Pull request merged**
